const Style = {
  primary: '#152039',
  secondary: '#2c364c',
  danger: '#dc3545',
  warning: '#ffc107',
  info: '#17a2b8',

  mainColor: '#152039',
  mainDisabledColor: '#2c364c',
  mainColorDarker: '#090432',
  mainColorLighter: '#303068',
  cleanColor: '#f5f5f5',
  cleanColorDarker: '#eeeeee',
  cleanColorLighter: '#ffffff',
  inputBorderColor: '#585858',
  inputHoverBorderColor: '#0c063f',
  inputFocusBorderColor: '#0c063f',
  textError: '#E12',
  btnFocus: '#cdcdcd',
  btnHover: '#003aa9',
  btnActive: '#0c6296',
  fontColorClear: '#fafafa',
  fontColorDark: '#212121',
  fontSizeSmall: '12px',
  backgroundColorGrey: '#F8F8F8',
  fontSizeDefault: '16px',
  fontSizeBig: '20px',
  boxShadowDefault: '0 1px 4px 0 rgba(0, 0, 0, 0.30)',
  borderRadiusRound: '18px',
  borderRadiusSquare: '4px',
  datatableRowColorOdd: '#fafafa',
  datatableRowColorEven: '#eeeeee',
  datatableRowColorHighlighted: '#d6d6d6',
  datatableRowColorSelected: '#bebebe',
  datatableFooterColorOdd: '#fafafa',
  datatablefooterColorEven: '#eeeeee',
  fontFamilyMulish: 'Mulish',
  fontColorDarkGrey: 'grey',
  fontColorLightGrey: 'hsl(0, 0%, 90%)',
  textSuccess: 'hls(120, 50%, 45%)',
};

export default Style;
